version: '3'

volumes:
  bundle:
  db:
  node_modules:

services:
  redis:
    image: redis:alpine
  db:
    image: nouchka/sqlite3:latest
    volumes:
      - db:/root/db
    stdin_open: true
    tty: true
  backend:
    container_name: 'learn-english-backend'
    build:
      context: backend
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - ./backend:/app
      - bundle:/usr/local/bundle
    tmpfs: /app/tmp
    depends_on:
      - db
      - redis
    tty: true
    stdin_open: true
    ports:
      - "3001:3000"
  frontend:
    container_name: 'learn-english-frontend'
    build:
      context: frontend
      dockerfile: Dockerfile
    command: "npm start"
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    depends_on:
      - backend
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
